# Stage 1: Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./


RUN npm install


COPY . .


RUN npm run build

# Stage 2: Production stage
FROM node:20-alpine AS runner

WORKDIR /app


COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/package.json ./package.json


ENV NODE_ENV=production


EXPOSE 5000


CMD ["node", "dist/server.js"]